### PR TITLE
Fix Volume change

### PR DESCRIPTION
**Pull request by AirKing555**

### CODE REVIEW

**Comment by Apollon77** [comment]
Is this really the solution? As I understood so far the cset numid 1 is also used to select the sound output to the first soundcard ... and set the output level ... Your change removes the "numid 1" ...

**Comment by AirKing555** [comment]
numid = 1 does not always indicate the correct control channel
Here is my example
 amixer controls
numid = 14, iface = CARD, name = 'Front Headphone Jack'
numid = 13, iface = CARD, name = 'Mic Jack'
numid = 15, iface = CARD, name = 'Speaker Phantom Jack'
numid = 12, iface = MIXER, name = 'Master Playback Switch'
numid = 11, iface = MIXER, name = 'Master Playback Volume'
numid = 2, iface = MIXER, name = 'Headphone Playback Switch'
numid = 1, iface = MIXER, name = 'Headphone Playback Volume'
numid = 20, iface = MIXER, name = 'PCM Playback Volume'
numid = 10, iface = MIXER, name = 'Mic Boost Volume'
numid = 6, iface = MIXER, name = 'Mic Playback Switch'
numid = 5, iface = MIXER, name = 'Mic Playback Volume'
numid = 9, iface = MIXER, name = 'Capture Switch'
numid = 8, iface = MIXER, name = 'Capture Volume'
numid = 7, iface = MIXER, name = 'Auto-Mute Mode'
numid = 17, iface = MIXER, name = 'Beep Playback Switch'
numid = 16, iface = MIXER, name = 'Beep Playback Volume'
numid = 4, iface = MIXER, name = 'Speaker Playback Switch'
numid = 3, iface = MIXER, name = 'Speaker Playback Volume'
numid = 19, iface = PCM, name = 'Capture Channel Map'
numid = 18, iface = PCM, name = 'Playback Channel Tap

**Comment by Apollon77** [comment]
As I understood it (and the best practices for raspies and others according to google) the cset with numid=1 also selects the headphone jack as audio output channel (cubietrucks for instance auto select hdmi for audio out, so numid=1 is needed to select the correct output)

What about the following idea: in "start" we should have a set of the master volume to always 100% initially, because then the volume method can work with the phone jack volume level in general, or?!

**Comment by AirKing555** [comment]
I proposed a universal remedy.
As I wrote not for all devices NUMID = 1 corresponds to the output channel to which the actual speakers connected. I have two devices over a single output sound. And they do not meet NUMID = 1

**Comment by Apollon77** [comment]
Hm ... Bluefox?
I only have basic/theoretical knowledge on this numid stuff ... and I do not use the adapter till now. My idea would be to accept the pull request and make sure that Forum users test it at least with Raspi's, Cubietrucks, NUC (inkl. a reboot) before officially publishing it to get the info that it really works for all systems

**Comment by AirKing555** [comment]
Тема поднималась давно. http://forum.iobroker.net/viewtopic.php?t=1939
решения так и нет, или сделайте в драйвере выбор NUMID или то что я предложил, достало уже при каждом обновлении править код под себя

**Comment by Apollon77** [comment]
Do we had a forum thread with infos and test results here? in the end it's online for all in the meantime ...  :-(

**Comment by GermanBluefox** [comment]
We have now `name="Master Playback Volume"` instead of` "numid=1"`
and this should work for all devices.

**Pull request merged**
